name: adminapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.3.3
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.14.1+3
  cupertino_icons: ^1.0.2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.1
  fluttertoast: ^7.1.1
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hive_generator: ^0.8.1
  http: ^0.12.2
  image_picker: ^0.6.7+11
  lottie: ^0.6.0
  path_provider: ^1.6.18
  pinch_zoom: ^0.1.0
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
flutter:
  uses-material-design: true
  assets:
    - assets/
